### ISSUE TITLE
How about event loop?

### ISSUE THREAD

**Issue by yisar** [HiRoFa/quickjs_es_runtime#31]

**Comment by andrieshiemstra** [comment]
Hi Yisar,

this is basicly my implementation of an event loop
https://github.com/HiRoFa/quickjs_es_runtime/blob/master/src/utils/single_threaded_event_queue.rs

EsRuntime has an instance of that queue

Everyting you want to do with the QuickJsRuntime is added to that queue as a job and runs in the single thread which has access to the instance of QuickJsRuntime.

adding a job to the "loop" is done like this
```rust
// create a new Runtime
let rt = EsRuntimeBuilder::new()
        .build();
// add a job to the loop
rt.add_to_event_queue(|q_js_rt: &QuickJsRuntime| {
    // here we are in the event loop thread, we can do things with q_js_rt here
});
```

The result of add_to_event_queue is a Future so you can .await it if you are running async.

Thank you for your interest in this project and I hope this answers your question, if not please let me know.

**Comment by yisar** [comment]
Thank you for your answer, it is very useful.  Single-threaded event queue looks good.
