### ISSUE TITLE
use JS_UpdateStackTop

### ISSUE THREAD

**Issue by andrieshiemstra** [HiRoFa/quickjs_es_runtime#50]
after init of the runtime use this set the correct stack top

and maybe set the max size as a large number by default

**Comment by andrieshiemstra** [comment]
i've been unable to get this to work in a sensible way, will try later for a 0.6.1 release

**Comment by andrieshiemstra** [comment]
Hi @SreeniIO 

i'd like to work towards a 0.7 release and like to know if the above code fixes your issue with max_stack_size not working

it seems to work for me

**Comment by SreeniIO** [comment]
I guess it works fine, haven't seen any issue so far related to stack size.

**Comment by andrieshiemstra** [comment]
this tickets was created to reenable the option to set a max stack size as discussed here

https://github.com/HiRoFa/quickjs_es_runtime/issues/48#issuecomment-869563288

i did some preliminary testing and it seems to function properly now...
