### ISSUE TITLE
Ability to load pre-compiled modules

### ISSUE THREAD

**Issue by SreeniIO** [HiRoFa/quickjs_es_runtime#56]
Hi there!
I'm able to pre-compile a JS/TS function and save as bytecode and later execute using `run_compiled_function`.

I'm looking for a similar option for pre-compiling some modules (e.g. lodash, date-fns etc) to avoid loading and compiling on every invocation.

May be `ByteCodeModuleLoaderAdapter` that will be almost similar to `ScriptModuleLoaderAdapter` except for the below line.

https://github.com/HiRoFa/quickjs_es_runtime/blob/0225d27632fae2d14a955f3b4ac02bc9742baa63/src/quickjsruntimeadapter.rs#L83

Any thoughts?

**Comment by andrieshiemstra** [comment]
so the advantage would be the ability to load a compiled module from disk? for faster startup?

allthough i gues there are practical uses for that i would like to point out that while you say "loading and compiling on every invocation." modules are actually kept cached in every JSContext (Realm) in a loaded_modules list (see quickjs.c) and once compiled they are not compiled again unless you init a new Realm.. 

Havinbg said that i am still very much open to the idea of a CompiledModuleLoader (or as an option in scriptmodueloader)

**Comment by SreeniIO** [comment]
In my case, a new context is created for every call. Hence, this would be of great help. Thanks

**Comment by andrieshiemstra** [comment]
ok, i slammed the code in without testing or even trying to run it.. (so it needs some QC :)) but you could test to see if it works..

**Comment by andrieshiemstra** [comment]
todo: make from_bytecode accept a &Vec<u8> so we can alter CompiledModuleLoader to return a &Vec<u8> so you don't have to clone or create thge buffer every time you eval a compiled module

**Comment by andrieshiemstra** [comment]
todo, check if module (eval and execution) still works if we drop the buffer

**Comment by SreeniIO** [comment]
Great. Will test it out and let you know.

**Comment by SreeniIO** [comment]
Made the below changes
1. Pass the current realm ref to CompiledModuleLoader functions (required to compile the source when loading for the first time)
2. Return the bytes as Arc<Vec<u8>> instead of &Vec<u8>

**Comment by andrieshiemstra** [comment]
this issue does make me wonder if we're not overcomplicating things... we could also just make an option in the module loading logic to allways first compile modules to bytecode and cache that so it gets reused in every new realm (do you create a new realm for every new call or a new runtime?)

using a simple #[cached(size=100)] annotated function we could probably get the same performance benefit without the extra CompiledModuleLoader

**Comment by SreeniIO** [comment]
I instantiate only one runtime and create a new realm on every new call (for security reasons and to keep all the calls isolated & stateless).

I'm not sure how the cached annotation would work here as the parameters would include a realm.

**Comment by andrieshiemstra** [comment]
> I instantiate only one runtime and create a new realm on every new call (for security reasons and to keep all the calls isolated & stateless).
> 
> I'm not sure how the cached annotation would work here as the parameters would include a realm.

i'll look into this later but to answer your question, you can create a custom key in that annotation
```rust
#[cached(
    key = "String",
    size = 10000,
    time = 3600,
    result = true,
    convert = r#"{ format!("{}://{}/{:?}", scheme, domain_port, session.get_env()) }"#
)]
async fn get_info(
    scheme: &str,
    domain_port: &str,
    session: GrecoSession,
) -> Result<OpenApi, JsError> {
   todo!()
}

```

**Comment by SreeniIO** [comment]
Thanks, closing this for now... as we have CompiledModuleLoader in place.
