### ISSUE TITLE
Option to disable features - console, setTimeout, setInterval

### ISSUE THREAD

**Issue by SreeniIO** [HiRoFa/quickjs_es_runtime#58]
It would be nice to expose options in the builder to opt-out of certain features i.e. console, setInterval etc.

For instance I would like to override the default console.log implementation to include some session information along with the log message and prevent users from using setInterval, setTimeout.

Let me know if you would like me to raise a PR for this. I'm thinking of adding the following options to QuickJsRuntimeBuilder

- disable_features or exclude_features

or an option for each feature

- disable_console_feature
- disable_set_timeout_feature
- disable_set_interval_feature

**Comment by andrieshiemstra** [comment]
for the feature part i agree, they should all be features in Cargo.toml which are enabled by default

I'd like to add a console_formatter option to the builder so you don't need to reimplement the whole console feature just to log differently, ill open a new issue for that.. #59

Lastly, we also need to examine the default features available in quickjs (like os.) we need to be able to disable those as well (https://bellard.org/quickjs/quickjs.html#Standard-library)

**Comment by andrieshiemstra** [comment]
Ah good to know!

Regarding the logger: wouldn't you rather implement your own facade for the log crate? seems simple enough 
https://github.com/Ereski/simple-logging/blob/master/src/lib.rs

And that way you also get your logging from rust...

The current console feature uses that facade
https://crates.io/crates/log

**Comment by SreeniIO** [comment]
The logs from JS runtime would be user logs (functional) and would like to keep them separate from the rust logs (dev/technical).

Also I don't want to include the session context in the log message itself, instead handle it internally to route to different topic/user (get's pushed to the user's browser console ;) even before generating the log message. Also, our Logger.log supports dynamic number parameters like the browser console.log & any JS objects, not just string.

**Comment by SreeniIO** [comment]
Here is a sample on how it's logged on the server, and how it shows up on the users's browser.

```javascript
Logger.info("log from the server", 123, false, true, new Date(), {key: "any js object"});
```

![image](https://user-images.githubusercontent.com/8140606/146972847-c27f3562-543c-4d34-add8-97067f310b26.png)

**Comment by andrieshiemstra** [comment]
> Here is a sample on how it's logged on the server, and how it shows up on the users's browser.
> 
> ```js
> Logger.info("log from the server", 123, false, true, new Date(), {key: "any js object"});
> ```
> 
> ![image](https://user-images.githubusercontent.com/8140606/146972847-c27f3562-543c-4d34-add8-97067f310b26.png)

that's actually very cool! for GreenCopperServer I was planning to implement something like that with cassandra as a back-end. Do you use Kafka to send logs to the client via something like websockets/messagequeue or is it all custom code?

**Comment by andrieshiemstra** [comment]
i made all 4 features optional.. please let me know if this fixes this issue

**Comment by SreeniIO** [comment]
We use Kafka & websocket.

**Comment by SreeniIO** [comment]
> i made all 4 features optional.. please let me know if this fixes this issue

Yes, thank you!
