### ISSUE TITLE
Panicked when running multiple promises concurrently

### ISSUE THREAD

**Issue by SreeniIO** [HiRoFa/quickjs_es_runtime#62]
Hi there!,
When running multiple promises like shown in the below sudo code, it got panicked once and am unable to reproduce at will. Hopefully you can figure out what's going on from the below line number that's displayed on the terminal running the rust executable.

https://github.com/HiRoFa/quickjs_es_runtime/blob/040a57a565bffc71488067b71c5d604832c9a771/src/quickjs_utils/functions.rs#L931

### sudo code block
await Promise.all(items.map(async (item) => {
 ... callbacks to rust...
  await Promise.all(... callbacks to rust...);
});

### Terminal Log
```
thread '<unnamed>' panicked at 'already borrowed: BorrowMutError', /xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/quickjs_runtime-0.7.0/src/quickjs_utils/functions.rs:942:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
xxx: /xxx/target/release/build/libquickjs-sys-b91a79c760ce47e7/out/quickjs/quickjs.c:5789: gc_free_cycles: Assertion `p->gc_obj_type == JS_GC_OBJ_TYPE_JS_OBJECT || p->gc_obj_type == JS_GC_OBJ_TYPE_FUNCTION_BYTECODE' failed.
```
Cargo.toml
quickjs_runtime = { version = "0.7.0", default-features = false, features = [] }

**Comment by andrieshiemstra** [comment]
yeah i gues i can see an issue with how things work at line 971 (a callback is called while CALLBACK_REGISTRY is borrowed)

so if you create or call a callback from a callback.. thing will fall apart.. i'll look into it asap

**Comment by andrieshiemstra** [comment]
certain this is fixed now, lime 942 is indeed borrowing the cb registry.
