### ISSUE TITLE
Tokio Version in cargo.toml

### ISSUE THREAD

**Issue by dgildeh** [HiRoFa/quickjs_es_runtime#75]
I just updated to your latest version and then got Rust issues and had to update my cargo.toml to use Tokio v 1.4.0 because of a conflict with the version required in this library. This version is 2 years old, could you update your dependencies to use the latest version of Tokio? (1.28.0)

**Comment by andrieshiemstra** [comment]
done, please note that the current main branch (0.10) is quire the overhaul which is not yet complete but should make a better foundation for a quickjs specific wrapper..
i'm also planning to move a typescript parser to GreenCopperRuntime and then publish a first version of GreenCopperRuntime to crates.io

**Comment by SreeniIO** [comment]
@andrieshiemstra you may have to remove the tokio feature memchr which is no longer available in the latest version of tokio.

**Comment by andrieshiemstra** [comment]
> @andrieshiemstra you may have to remove the tokio feature memchr which is no longer available in the latest version of tokio.

done, thanks!

**Comment by dgildeh** [comment]
Thanks for the quick response! I'll test it out as soon as the next crate is pushed.

**Comment by dgildeh** [comment]
Fixed the TypeScriptPreProcessor error by locking to the last commit before your 0.10 rewrite:

typescript_utils = {git="https://github.com/HiRoFa/typescript_utils", rev="7799c990a328df2f07ac6ca7276f7bf4006f7e02"}
