### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by andrieshiemstra** [HiRoFa/quickjs_es_runtime#76]
I'm thinking about adding typescript support directly in quickjs_runtime instead of a separate crate, it would be an optional feature.

Things we could do:
* [ ] native support for typescript
* [ ] optional caching of transpiled/compiled code (and optional disk backed)
* [ ] parse .map files and return correct stacktraces on errors
* [ ] serverside React support out of the box
  * status update: playing with this at https://github.com/HiRoFa/GreenCopperCmd/blob/main/scripts/ssr.ts,
  * you can run it with `cargo run -- -f scripts/ssr.ts`

i'd like to hear your thoughts on this

**Comment by xHyroM** [comment]
you can use SWC

**Comment by xHyroM** [comment]
i should move it here because typescript support is really important, annoying build tools heh

**Comment by andrieshiemstra** [comment]
> i should move it here because typescript support is really important, annoying build tools heh

Thank you for your feedback!

**Comment by andrieshiemstra** [comment]
avail in 0.11.0

**Comment by xHyroM** [comment]
cool 👍
