### ISSUE TITLE
fork quickjs

### ISSUE THREAD

**Issue by andrieshiemstra** [HiRoFa/quickjs_es_runtime#77]
there are quite some patches and pull request lying around the web i'd actually like to use 
like:
* https://github.com/bellard/quickjs/pull/143 (should help with better stack trace mapping when transpiling to typescript)

so i think i need to 
* [x] fork libquickjs-sys from https://github.com/theduke/quickjs-rs/tree/master/libquickjs-sys
  * [x] make the quickjs fork to use configurable via feature
* [x] use my own libquickjs-sys in quickjs_runtime
* [x] fix compilation of quickjs-ng
* [ ] fix compilation of openwebf

**Comment by proehlen** [comment]
Only mention it in case you haven't seen it but this seems to be a semi-recent fork that has had some improvements made to it:
https://github.com/openwebf/quickjs

Might not be what you are after though.

**Comment by andrieshiemstra** [comment]
> Only mention it in case you haven't seen it but this seems to be a semi-recent fork that has had some improvements made to it: https://github.com/openwebf/quickjs
> 
> Might not be what you are after though.

@proehlen thanks! Will look into it

**Comment by andrieshiemstra** [comment]
the openwebf variant seems to have some bugs, i'm just going to make my own fork of libquickjs-sys foirst and base it on the new release from bellard (https://bellard.org/quickjs/Changelog)

**Comment by andrieshiemstra** [comment]
this one also seems to be actively maintained

https://github.com/quickjs-ng/quickjs

**Comment by andrieshiemstra** [comment]
first steps have been taken, i now use hirofa-quickjs-sys as libquickjs-sys which uses the latest release from bellard.org
it also includes a feature flag to switch to quickjs-ng and the openwebf variant but those do not yet work...
